export const Authentication ={
    LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    LOGIN_FAILED :'USER_LOGIN_FAILED'
}

export const client ={
    CLIENT_LIST_SUCCESS:'CLIENT_LIST_SUCCESS',
    CLIENT_LIST_FAILED :'CLIENT_LIST_FAILED',
    CLIENT_ACTIVATE: 'CLIENT_ACTIVATE',
    CLIENT_DEACTIVATE: 'CLIENT_DEACTIVATE',
};

export const form ={
    FORM_LIST_SUCCESS:'FORM_LIST_SUCCESS',
    FORM_LIST_FAILED :'FORM_LIST_FAILED',
    FORM_ITEM_SUCCESS:'FORM_ITEM_SUCCESS',
    FORM_ITEM_FAILED :'FORM_ITEM_FAILED',
    FORM_ITEM_EDIT_SUCCESS:'FORM_ITEM_EDIT_SUCCESS',
    FORM_ITEM_EDIT_FAILED :'FORM_ITEM_EDIT_FAILED'

};

export const input ={
    INPUT_LIST_SUCCESS:'INPUT_LIST_SUCCESS',
    INPUT_LIST_FAILED:'INPUT_LIST_FAILED',
    INPUT_LIST_ADD_SUCCESS:'INPUT_LIST_ADD_SUCCESS',
    INPUT_LIST_REMOVE_SUCCESS:'INPUT_LIST_REMOVE_SUCCESS',
    INPUT_OPTION_LIST_ADD: 'INPUT_OPTION_LIST_ADD',
    INPUT_OPTION_LIST_REMOVE: 'INPUT_OPTION_LIST_REMOVE',
};

export const clientManager = {
    UNSET_REDIRECT: "UNSET_REDIRECT"
}