#  -Client
CLIENT_GET_SUCCESS = 'CLIENT_GET_SUCCESS'
CLIENT_GET_EMPTY = 'CLIENT_GET_EMPTY'
#  --List
CLIENT_GET_LIST_SUCCESS = 'CLIENT_GET_LIST_SUCCESS'
CLIENT_GET_LIST_EMPTY = 'CLIENT_GET_LIST_EMPTY'
