#  -Form
FORM_GET_SUCCESS = 'FORM_GET_SUCCESS'
FORM_GET_EMPTY = 'FORM_GET_EMPTY'
FORM_SET_SUCCESS = 'FORM_SET_SUCCESS'
FORM_SET_FAILED = 'FORM_SET_FAILED'
#  --List
FORM_GET_LIST_SUCCESS = 'FORM_GET_LIST_SUCCESS'
FORM_GET_LIST_EMPTY = 'FORM_GET_LIST_EMPTY'
